"""drop username column.

Revision ID: 73bbe32d3e64
Revises: 47180090d12a
Create Date: 2025-10-05 20:22:26.771548

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73bbe32d3e64"
down_revision = "47180090d12a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=80), autoincrement=False, nullable=True,
        ),
    )
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
