"""add ai models.

Revision ID: 742cfe2a9579
Revises: 7acda12a613c
Create Date: 2025-09-17 20:14:14.757833

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "742cfe2a9579"
down_revision = "7acda12a613c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_follow_ups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("generated_message", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SENT", "ACKNOWLEDGED", name="followupstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_follow_ups_recipient_id"),
        "task_follow_ups",
        ["recipient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_follow_ups_task_id"),
        "task_follow_ups",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_follow_ups_task_id"), table_name="task_follow_ups")
    op.drop_index(op.f("ix_task_follow_ups_recipient_id"), table_name="task_follow_ups")
    op.drop_table("task_follow_ups")
    # ### end Alembic commands ###
