"""add soft delete to chats.

Revision ID: add_soft_delete_chats
Revises: fb88f2600f1c
Create Date: 2025-01-02 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_soft_delete_chats"
down_revision = "fb88f2600f1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("deleted", sa.Boolean(), nullable=False, server_default="false"))
    op.create_index("ix_chats_deleted", "chats", ["deleted"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chats_deleted", table_name="chats")
    op.drop_column("chats", "deleted")
    # ### end Alembic commands ###
