"""add new fields for user.

Revision ID: aa6c089b8211
Revises: 742cfe2a9579
Create Date: 2025-09-27 18:18:59.531189

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = "aa6c089b8211"
down_revision = "742cfe2a9579"
branch_labels = None
depends_on = None



def upgrade() -> None:
    """Run the migration."""
    # Add nullable column first
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=255), nullable=True),
    )
    op.add_column("users", sa.Column("last_login", sa.DateTime(), nullable=True))

    # --- Fix for 'is_verified' (Boolean NOT NULL) ---
    # 1. Add column as nullable, with a server default to populate existing rows
    op.add_column(
        "users",
        sa.Column("is_verified", sa.Boolean(), nullable=True, server_default=expression.true()),
    )
    # 2. Alter column to set NOT NULL and remove the temporary server default
    op.alter_column(
        "users",
        "is_verified",
        nullable=False,
        server_default=None,
    )
    # --- End Fix for 'is_verified' ---

    # --- Fix for 'refresh_token_param' (Integer NOT NULL) ---
    # 1. Add column as nullable, with a server default (the intended default of 1)
    op.add_column(
        "users",
        sa.Column("refresh_token_param", sa.Integer(), nullable=True, server_default="1"),
    )
    # 2. Alter column to set NOT NULL and remove the temporary server default
    op.alter_column(
        "users",
        "refresh_token_param",
        nullable=False,
        server_default=None,
    )

def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login")
    op.drop_column("users", "refresh_token_param")
    op.drop_column("users", "is_verified")
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
